// Writes server/src/brandpng.js: the app icon PNG (acr-daily-icon-512.png) embedded for the server, which serves
// it at /brand/acr-daily-icon-512.png (the Discord bot's avatar and embeds). Run after changing the logo:
//   node brand/make_brandpng.mjs        (from the repository folder, after client/make_icon.py)
import { readFileSync, writeFileSync } from 'node:fs';

const b64 = readFileSync(new URL('./acr-daily-icon-512.png', import.meta.url)).toString('base64');
writeFileSync(new URL('../server/src/brandpng.js', import.meta.url),
  '// Generated by brand/make_brandpng.mjs from brand/acr-daily-icon-512.png: do not edit.\n' +
  `export const ICON_PNG = '${b64}';\n`);
console.log('server/src/brandpng.js:', b64.length, 'base64 characters');
